site_name: Data Scientist Roadmap

theme: 
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate 

nav:
  - Home: index.md
  - Roadmap: 
    - Quem é?: Roadmap/dataScientist.md
    - Inteligência Artificial: Roadmap/artificialInteligence.md
    - Machine Learning: Roadmap/machineLearning.md
    - Generative AI: Roadmap/generativeAI.md
  - Appendices: appendices.md
  - References: references.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 4
